DefactoSoftware/Hours

Gemfile
Gemfile.lock
app/controllers/projects_controller.rb
app/helpers/markdown_helper.rb
app/views/projects/_form.html.haml
app/views/projects/_project_detail.html.haml
db/migrate/20150102125918_add_description_to_project.rb
db/schema.rb
spec/features/user_manages_projects_spec.rb

[READY] users can add a (markdown) description to projects

---

app/controllers/entries_controller.rb
app/models/entry_csv_generator.rb
app/models/report.rb
app/views/entries/index.html.haml
config/locales/en.yml
spec/features/user_downloads_entries_spec.rb
spec/models/entry_csv_generator_spec.rb

Should be really easy to allow any collection of entries to be downloaded as CSV from here

[READY] allow user entries to be downloaded as CSV

---

app/assets/stylesheets/_projects.css.scss
app/controllers/projects_controller.rb
app/models/project.rb
app/views/projects/_form.html.haml
app/views/projects/_project.html.haml
app/views/projects/_project_detail.html.haml
config/locales/en.yml
config/locales/nl.yml
db/migrate/20141217151026_add_budget_to_project.rb
db/schema.rb
spec/factories/projects.rb
spec/models/project_spec.rb

[READY] add budget attribute to project

---

app/assets/stylesheets/_project.css.scss
app/assets/stylesheets/base/_buttons.scss
app/assets/stylesheets/base/_variables.scss
app/views/projects/_form.html.haml
app/views/projects/edit.html.haml
config/locales/en.yml
config/locales/nl.yml
spec/features/user_manages_archived_projects_spec.rb

[READY] change the checkbox of archive to a button

---

app/assets/javascripts/application.js
app/models/project.rb
app/validators/client_billable_validator.rb
app/views/projects/_form.html.haml
config/locales/en.yml
config/locales/nl.yml
spec/features/user_manages_projects_spec.rb
spec/models/project_spec.rb

[READY] Add validation for billable/client

---

app/models/entry_filter.rb
app/models/entry_query.rb
app/views/billables/_filters.html.haml
app/views/billables/index.html.haml
app/views/entries/_filters.html.haml
app/views/reports/_filters.html.haml
app/views/reports/index.html.haml
config/locales/en.yml
spec/models/entry_filter_spec.rb
spec/models/entry_query_spec.rb

This should make it really easy to add more filters ^^

[READY] pull out filter_params and add archived/unarchived filter to reports

---

app/assets/stylesheets/_components.css.scss
app/assets/stylesheets/_project.scss
app/assets/stylesheets/_tagger.scss
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/base/_forms.scss
app/assets/stylesheets/base/_variables.scss
app/inputs/switch_input.rb
app/views/projects/_form.html.haml
app/views/projects/_project_detail.html.haml
app/views/projects/edit.html.haml
spec/features/user_manages_archived_projects_spec.rb
spec/features/user_views_project_audit_trail_spec.rb

clean up new project and edit project views

---

app/models/time_series/monthly_time_series.rb
app/models/time_series/weekly_time_series.rb
app/models/time_series/yearly_time_series.rb
app/views/application/_entry_form.html.haml
lib/tasks/create_user.rake
spec/features/user_manages_own_hours_spec.rb

For when time zone is set and does not match server time.
Were tests passing locally for anyone else?

Change Date.today to Date.current

---

app/controllers/billables_controller.rb
app/models/billable_list.rb
app/models/client.rb
app/models/project.rb
app/views/billables/_entries.html.haml
app/views/billables/_projects.html.haml
app/views/billables/index.html.haml
db/migrate/20150212144126_add_index_on_billable_and_billed.rb
db/migrate/20150212144126_add_index_on_projects_billable.rb
db/schema.rb
spec/features/user_manages_billables_spec.rb
spec/models/billable_list_spec.rb

Huge performance boost on `/billables`, collab with @martin16877

Billable performance

---

app/models/entry_filter.rb
app/models/entry_query.rb
app/models/user.rb
app/views/reports/_filters.html.haml
config/locales/en.yml
config/locales/nl.yml
spec/models/entry_filter_spec.rb

add user filter to reports

---

app/assets/stylesheets/_tagger.scss
app/assets/stylesheets/base/_variables.scss

Addressing issue https://github.com/DefactoSoftware/Hours/issues/285

[READY] fix hashtag displacement

---

app/models/entry_query.rb

Makes sense to filter dates inclusively instead of exclusively...

Filter by date inclusively

---

app/assets/stylesheets/_entries.scss

Addressing issue https://github.com/DefactoSoftware/Hours/issues/290

[READY] fix entries table

---

app/assets/javascripts/application.js
app/assets/javascripts/i18n.js.coffee
app/views/application/_entry_form.html.haml
app/views/billables/_filters.html.haml
config/locales/en.yml
config/locales/nl.yml
spec/features/user_manages_own_hours_spec.rb
spec/features/user_registers_time_spec.rb

[READY] fixed pikaday calendar for billables view

---

.sample.env
Gemfile
Gemfile.lock
config/environments/production.rb

fixes #305 
Needs a bucket on amazon

[ready] Add aws config for paperclip

---

app/assets/javascripts/application.js
app/assets/javascripts/billables.js
app/controllers/application_controller.rb
app/controllers/billables_controller.rb
app/controllers/entries_controller.rb
app/controllers/hours_controller.rb
app/controllers/mileages_controller.rb
app/controllers/projects_controller.rb
app/controllers/reports_controller.rb
app/helpers/application_helper.rb
app/models/entry_csv_generator.rb
app/models/hour.rb
app/models/mileage.rb
app/views/application/_mileages_entry_form.html.haml
app/views/billables/_mileages_entries.html.haml
app/views/billables/index.html.haml
app/views/entries/_hours_table.html.haml
app/views/entries/_mileages_table.html.haml
app/views/entries/edit.html.haml
app/views/entries/index.html.haml
app/views/projects/index.html.haml
app/views/reports/_hours_reports.html.haml
app/views/reports/_mileages_reports.html.haml
config/locales/en.yml
config/locales/nl.yml
config/routes/subdomain_present.rb
spec/features/user_manages_clients_spec.rb
spec/models/entry_csv_generator_spec.rb
spec/support/session_helper.rb

fixes:
- removed mileages entry path since it wasn't used anymore  
- removed title conditions since the mileages path was removed
- tabs, 
- fixed view warning 
- removed to_object from application_controller and rewritten to methods in models
- fixed pagination working with tabs
- you no longer get redirected to the wrong tab when entering mileage entry (still not working on filter in reports view)
- added hours and mileages to CSV download
- fixed CSV download on personal entries to download all entries and not just the first page
- fixed autocomplete on tags in hours entry form
- fixed select all entries checkbox in billables view
- fixed some I18N typo's and missing translations

[READY] mileages fixes

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_activity-feed.scss
app/assets/stylesheets/_navbar.scss
app/assets/stylesheets/application.css.scss
app/helpers/application_helper.rb
app/views/application/_avatar.html.haml
app/views/application/_entry.html.haml
app/views/application/_navbar.html.haml
app/views/audits/_audits.html.haml
app/views/clients/_project.html.haml
app/views/projects/_project.html.haml
app/views/projects/_project_detail.html.haml
app/views/users/edit.html.haml

per @sn3p idea
added easter egg shaped avatars

[READY] add easter eggs

---

app/helpers/application_helper.rb
app/views/application/_entry.html.haml
app/views/application/_navbar.html.haml
app/views/audits/_audits.html.haml
app/views/clients/_project.html.haml
app/views/projects/_project.html.haml
app/views/projects/_project_detail.html.haml
app/views/users/edit.html.haml
config/locales/nl.yml

needs to be merged to development before mileages gets added to production.
problem was the easter_check trying to read data from an empty array. Didn't show up earlier because it was on a holiday so the array wasn't empty. 
also fixed missing translation bug in audits on dutch setting

[READY] fix for easter egg bug and translation missing

---

app/views/reports/_filters.html.haml

found out pikaday works in billables, but not in reports.

[READY] hotfix pikaday on reports page

---

config/application.rb

set I18n available locales to en and nl

[READY] translation hotfix

---

app/views/application/_hours_entry_form.html.haml
app/views/application/_mileages_entry_form.html.haml
app/views/projects/index.html.haml

because it caches the authenticity token that is used in CSRF prevention

[HOTFIX] do not cache the entry form

---

lib/hours.rb

Fixed typo in hours fail message

---

app/models/account.rb
config/locales/en.yml
config/locales/nl.yml
spec/models/account_spec.rb

[READY] Fixed translation for error messages

---

app/views/layouts/landing.html.haml
app/views/pages/_footer.html.haml
app/views/pages/team.html.haml

[READY] Landingpage links

---

app/controllers/users_controller.rb
config/locales/en.yml
config/locales/nl.yml
spec/features/user_edits_account_spec.rb

This should fix #341, makes it more clear what's happening :)

fix account update flashes

---

config/boot.rb

As per http://refactorcop.com/DefactoSoftware/Hours

Tiny deprecation fix

---

Dockerfile
README.md
bin/docker_setup
config/database.yml.example
config/secrets.yml
docker-compose.yml
spec/spec_helper.rb

This commit adds the necessary configuration and Docker related
files to allow the application and dependencies to run within Docker
containers. Utilizing docker-compose, this also allows the orchestration
of the separate database, cache, and jobs containers apart from the
main application.
_Note:_ I did this for a [tutorial](https://coderjourney.com/convert-rails-app-to-docker/) that I was creating, if it's not a contribution that is wanted I completely understand.
For this to work you would need to add a few more environment variables to your `.env`:
``` .env
POSTGRES_HOST=db
POSTGRES_USER=hours
POSTGRES_PASSWORD=secure_password
```
And you would also need to set up a `database.yml` that utilizes these values:
``` yaml
default: &default
adapter: postgresql
host: <%= ENV["POSTGRES_HOST"] …
```

Configure for Docker based development

---

app/views/billables/_hours_entries.html.haml
app/views/billables/index.html.haml

This will make a lot less calls on the database (3 less for every hour)
This is for 28 hour entries:
OLD:
```
Account Load (0.4ms)  SELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."subdoma
User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [
Project Load (0.4ms)  SELECT "projects".* FROM "projects" WHERE "projects"."billable" = $1 AND "projects"."arch
Hour Exists (0.4ms)  SELECT  1 AS one FROM "hours" WHERE "hours"."project_id" = $1 AND "hours"."billed" = $2 LI
Hour Exists (0.5ms)  SELECT  1 AS one FROM "hours" WHERE "hours"."project_id" = $1 AND "hours"."billed" = $2 LI
Hour Load (0.7ms)  SELECT "hours".* FROM "hours" WHERE "hours"."project_id" = $1 AND "hours"."billed" = $2  [["
Project Load …
```

less db requests

---

Gemfile
Gemfile.lock

https://nvd.nist.gov/vuln/detail/CVE-2017-0889

update paperclip due to cve

---

app/assets/javascripts/application.js
app/assets/javascripts/i18n.js.coffee

Solve [issues/442](https://github.com/DefactoSoftware/Hours/issues/442)
- Prevent undefined language for I18n when not find the translation in i18n.js.coffee use english as default
- Add a Brazilian Portuguese to i18n.js.coffee

fix entry hours submit form desappeared locale pt br

---

app/assets/javascripts/application.js
config/environments/development.rb

- Add improvements in javascript application
- Fix TypeError no implicit conversion of Integer into String

add application javascript improvements
